### ISSUE TITLE
Context menu is cropped

### ISSUE THREAD

**Issue by maelomanontroppo** [uxbox/uxbox#1223] opened 2021-09-17 13:37 UTC
**Describe the bug**
Within the right panel, when you open the Component contexte menu, it won't overlay the panel. You can't read the full menu texts.

**To Reproduce**
1.  Select a component on artboard
2. Search for its name in right panel
3. click on its options menu (three little points)

**Screenshots**
![image](https://user-images.githubusercontent.com/90381769/133791569-ece1f6e7-996e-4934-9447-c9f84570db00.png)

**Desktop :**

-   OS: Windows
-   Browser : Chrome
-   Version Version 93.0.4577.82 (Build officiel) (64 bits)

**Environment :**
SAAS (https://design.penpot.app)

**Comment by myfunnyandy** [comment] 2021-09-20 09:16
Thanks for raising the issue. We've added it to Taiga and will fix it eventually: https://tree.taiga.io/project/penpot/issue/2051

**Comment by mlgarchery** [comment] 2021-09-20 13:20
Duplicate of https://github.com/penpot/penpot/issues/1101 .
On taiga https://tree.taiga.io/project/penpot/issue/1900

**Comment by myfunnyandy** [comment] 2021-09-21 06:54
Thanks for noticing @mlgarchery, I've also deleted the duplicated taiga issue.

**Closed as completed** 2021-09-21 06:55 UTC
Labels: bug, managed on taiga
