### ISSUE TITLE
bug: a svg file will turn to all black after upload

### ISSUE THREAD

**Issue by SimsonW** [uxbox/uxbox#2605] opened 2022-11-27 09:21 UTC
### Steps To Reproduce

1. download the svg file: https://www.svgrepo.com/download/430007/soap-bodywash-bodylotion.svg
2. upload this file to Penpot

### Expected behavior

the svg show be showed like that 
![image](https://user-images.githubusercontent.com/32561668/204127804-1ce20a55-0da7-4bec-92e6-5068e2d10688.png)

### Actual behavior

However the svg is turned to all black in Penpot
![image](https://user-images.githubusercontent.com/32561668/204127840-5d9d762c-96b5-4e55-be86-1ddf1420d0f0.png)

**Comment by myfunnyandy** [comment] 2022-11-29 16:08
Hi, I've added the issue to our issue tracker: https://tree.taiga.io/project/penpot/issue/4541
We'll take a look at it and will try to fix it.

**Comment by JustinBack** [comment] 2022-12-08 08:39
Can confirm this happens on FontAwesome DuoTone SVGs as well.
![image](https://user-images.githubusercontent.com/40178814/206398910-21b0792c-fec9-454c-a3f8-2cff1496775c.png)

Though as a component it shows just fine.


![image](https://user-images.githubusercontent.com/40178814/206398980-fa4b8180-6e9d-4289-999f-ae3c2057c185.png)

Any ETA/Info if this is fixed in the next release?

**Comment by pabloalba** [comment] 2022-12-28 07:42
Hi!

The problem is that the fill / stroke info is in svgs styles, instead of in the paths, and we aren't importing that info:

```
<?xml version="1.0" encoding="UTF-8"?>
<!-- Uploaded to: SVG Repo, www.svgrepo.com, Transformed by: SVG Repo Tools -->
<svg xmlns="http://www.w3.org/2000/svg" width="800px" height="800px" viewBox="0 0 32 32" data-name="Layer 1" id="Layer_1">
   <defs>
      <style>.cls-1,.cls-2,.cls-3{fill:none;stroke:#231f20;}.cls-1{stroke-miterlimit:10;}.cls-2{stroke-linecap:round;}.cls-2,.cls-3{stroke-linejoin:round;}.cls-3{stroke-width:2px;}</style>
   </defs>
   <title />
   <path class="cls-1" d="M15.49,13.5h1a5,5,0,0,1,5,5v7a3,3,0,0,1-3,3h-5a3,3,0,0,1-3-3v-7A5,5,0,0,1,15.49,13.5Z" />
   <rect class="cls-2" height="3" width="5" x="13.5" y="10.5" />
   <rect class="cls-2" height="3" width="3" x="14.5" y="7.5" />
   <path class="cls-2" d="M14.5,3.5h5a0,0,0,0,1,0,0v1a1,1,0,0,1-1,1h-4a0,0,0,0,1,0,0v-2A0,0,0,0,1,14.5,3.5Z" />
   <line class="cls-3" x1="16" x2="16" y1="6" y2="7" />
</svg>
```

It will take some time to implement, so it probably won't be fixed on the next release

**Closed as completed** 2023-01-31 13:47 UTC
Labels: bug, managed on taiga
