### ISSUE TITLE
bug: Blank page, Penpot not loading. 

### ISSUE THREAD

**Issue by autoantigen** [uxbox/uxbox#4518] opened 2024-04-25 09:58 UTC
### Steps To Reproduce

1. Penpot installed on the server using docker [docker-compose.yaml](https://raw.githubusercontent.com/penpot/penpot/main/docker/images/docker-compose.yaml)
2. Loading homepage - empty screen.

### Expected behavior

Page loaded without issues.

### Actual behavior

Empty page, 2 errors in browser console.

Same result in Firefox, Chrome and in incognito mode.

### Screenshots or video

![image](https://github.com/penpot/penpot/assets/11525373/48757102-3f63-428e-84bd-f590f8d33823)
![image](https://github.com/penpot/penpot/assets/11525373/4e50a00a-0fa3-4a90-889f-02634727f0c5)

### Environment (please complete the following information)

**Self hosted**
- Ubuntu version: `Ubuntu 22.04.3 LTS`
- Docker version 24.0.7, build afdd53b
- docker-compose version 1.29.2, build unknown

### Frontend Stack Trace

**Logs from frontend container**

```console
172.18.0.2 - - [25/Apr/2024:09:45:00 +0000] "GET / HTTP/1.1" 200 560359 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0"
172.18.0.2 - - [25/Apr/2024:09:45:01 +0000] "GET /js/config.js?ts=1713206204450 HTTP/1.1" 200 112 "https://penpot.x2y.dev/" "Mozilla/5.0 (X11; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0"
172.18.0.2 - - [25/Apr/2024:09:46:30 +0000] "GET / HTTP/1.1" 200 560359 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0"
172.18.0.2 - - [25/Apr/2024:09:46:31 +0000] "GET /js/config.js?ts=1713206204450 HTTP/1.1" 200 112 "https://penpot.x2y.dev/" "Mozilla/5.0 (X11; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0"
172.18.0.2 - - [25/Apr/2024:09:46:37 +0000] "GET / HTTP/1.1" 200 560359 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0"
172.18.0.2 - - [25/Apr/2024:09:46:38 +0000] "GET /js/config.js?ts=1713206204450 HTTP/1.1" 200 112 "https://penpot.x2y.dev/" "Mozilla/5.0 (X11; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0"
```

### Backend Stack Trace

**Logs from backend container**

```console
[2024-04-25 09:45:20.829] I app.metrics - action="initialize metrics"
[2024-04-25 09:45:20.844] I app.db - hint="initialize connection pool", name="main", uri="postgresql://penpot-postgres/penpot", read-only=false, with-credentials=true, min-size=0, max-size=60
[2024-04-25 09:45:20.894] I app.migrations - hint="running migrations", module=:app.migrations/migrations
[2024-04-25 09:45:21.237] I app.worker.executor - hint="executor started"
[2024-04-25 09:45:21.240] I app.redis - hint="initialize redis resources", uri="redis://penpot-redis/0", io-threads=3, worker-threads=3, connect?=nil
[2024-04-25 09:45:21.510] I app.msgbus - hint="initialize msgbus", buffer-size=128
[2024-04-25 09:45:22.200] I app.svgo - hint="initializing svg optimizer pool"
[2024-04-25 09:45:24.319] I app.http - hint="starting http server", port=6060, host="0.0.0.0"
[2024-04-25 09:45:24.341] I io.undertow - starting server: Undertow - 2.3.10.Final
[2024-04-25 09:45:24.351] I org.xnio - XNIO version 3.8.8.Final
[2024-04-25 09:45:24.358] I org.xnio.nio - XNIO NIO Implementation Version 3.8.8.Final
[2024-04-25 09:45:24.388] I org.jboss.threads - JBoss Threads version 3.5.0.Final
[2024-04-25 09:45:24.484] I app.storage.tmp - hint="started tmp cleaner", default-min-age="1h"
[2024-04-25 09:45:24.486] I app.loggers.database - hint="initializing database error persistence"
[2024-04-25 09:45:24.498] I app.worker - hint="registry initialized", tasks=14
[2024-04-25 09:45:24.504] I app.worker.cron - hint="started", tasks=9
[2024-04-25 09:45:24.540] I app.worker.executor - hint="monitor started", name="default"
[2024-04-25 09:45:24.541] I app.worker.dispatcher - hint="started"
[2024-04-25 09:45:24.546] I app.worker.runner - hint="started", id=0, queue="default"
[2024-04-25 09:45:24.550] I app.srepl - hint="initializing repl server", name="prepl", port=6063, host="localhost"
[2024-04-25 09:45:24.551] I app.worker.runner - hint="started", id=0, queue="webhooks"
[2024-04-25 09:45:24.559] I app.main - hint="welcome to penpot", flags="backend-openapi-doc,login-with-password,backend-api-doc,secure-session-cookies,v2-migration,backend-worker,smtp,email-verification,prepl-server", worker?=true, version="2.0.0-13164-g33bdf5e83"
```

### Additional context

It used to work fine, but after updating to v2 this issue started to happen quite randomly on different pages. Now it completely not working. 

Yesterday I did migration manually:

```
docker exec -ti penpot-penpot-backend-1 ./run.sh app.migrations.v2
```

And after restarting containers it started working but after few hours that issue came again.

**Logs from traefik**

```
time="2024-04-25T09:53:16Z" level=info msg="Configuration loaded from flags
```

**Comment by niwinz** [comment] 2024-05-23 11:14
It is very rare for this to start happening after a few hours, especially considering that the failure comes from the browser. You will not have any plugin or anything that is interfering. As you are saying, it does not seem to be a problem directly related to penpot, since according to the error that I see, if that error happens, it would happen from the beginning, not randomly over time, since the javascript files that the penpot application executes in your browser they do not change over time; They are static files.

**Comment by dgaiero** [comment] 2024-06-02 04:28
I'm experiencing the same exact issue (same blank page, looking at the console I see the same errors, etc.). It doesn't work on my mac on edge or safari, but my penpot instance does work on someone else's mac on edge. I did have this issue a while ago on my windows computer as well.

**Comment by sudo-eugene** [comment] 2024-08-06 18:03
I have a localhost:9001 setup + cloudflare tunnel through a .co domain.

the localhost url works fine, but my .co domain also stopped working after a time.

will keep testing/debugging and report back on what i find

**Comment by sudo-eugene** [comment] 2024-08-09 22:03
Hi Gents. I noticed that the same was happening with another application. Then realised that even if local browser cache/cookies/history was cleared, Cloudflare still was trying to cache and optimise for performance. 

I created a rule to bypass al caching and it's now working again

![e55cb3ce-99f6-408a-b704-0508650cbb36](https://github.com/user-attachments/assets/246787c1-113b-43fb-bd00-165c4e08ef64)

**Comment by dgaiero** [comment] 2024-08-09 22:14
Brilliant, thanks! I'll give it a try and see how it performs!

**Comment by Ratingthomas** [comment] 2024-08-10 09:10
Hi, I can confirm that the fix from @sudo-eugene indeed works. My penpot instance now works without issue. 

Maybe update the documentation to let people now that they need to disable caching?

**Comment by madalenapmelo-kp** [comment] 2024-08-14 10:14
Hi @autoantigen,

I'm closing this issue as it seems you have found the solution! Feel free to reopen it in case you need any further assistance :)

**Closed as completed by madalenapmelo-kp** 2024-08-14 10:14 UTC
Labels: bug, self-hosted

**Comment by autoantigen** [comment] 2024-09-17 09:56
> Hi @autoantigen,
> 
> I'm closing this issue as it seems you have found the solution! Feel free to reopen it in case you need any further assistance :)

Thanks! Have CloudFlare as well)
