### ISSUE TITLE
Middle mouse click in text editing with image in clipboard results with app crash.

### ISSUE THREAD

**Issue by Firstbober** [uxbox/uxbox#2177] opened 2022-08-20 14:50 UTC
**To Reproduce**

1. Add text element
2. Copy any image to clipboard
3. Start editing text and click middle mouse button on edit area

**Expected behavior**

App goes on and ignores image in my clipboard

**Actual behavior**

App shows `Internal Error` message.
 
**Screenshots**

[simplescreenrecorder-2022-08-20_16.43.40.webm](https://user-images.githubusercontent.com/22197465/185752322-d2202349-8b30-40d3-b1f9-bbebfb262070.webm)

**Desktop (please complete the following information):**
- OS (e.g. iOS): Manjaro Linux 5.19.1-2-MANJARO
- Browser & version (e.g. Chrome 89.0): Mozilla Firefox 103.0a1 (2022-06-14) (64-bit)

**Environment (please complete the following information):**
- Host (e.g. https://design.penpot.app, local instance): https://design.penpot.app

Frontend Stack Trace:
<details>

```
Unhandled Internal Error: can't access property "split", b is null [errors.cljs:195:7](https://design.penpot.app/js/app/main/errors.cljs)
TypeError: can't access property "split", b is null
    insertText text_editor_impl.js:370
    XLb text_editor.cljs:150
    handlePastedText editor.cljs:215
    exports editOnPaste.js:98
    React 12
    unstable_runWithPriority scheduler.production.min.js:19
    React 11
    Tib alpha.cljs:53
    Tqc alpha.cljs:260
    Vqc main.cljs:78
    <anonymous> append.js:2
```

</details>

**Comment by myfunnyandy** [comment] 2022-08-22 11:19
Hi @Firstbober, is this still happening to you? I could not reproduce the error.

**Comment by Firstbober** [comment] 2022-08-22 12:32
Yes, it is still happening. My guess is Firefox handles `PRIMARY` and `CLIPBOARD` clipboards in different manner. `PRIMARY` is used when pasting with mouse middle button on Linux X11. It is also not so simple to reproduce, I'm currently GPaste as my clipboard manager and the simplest way to reproduce the error is to grab an image from clipboard history.

**Comment by superalex** [comment] 2022-08-23 04:52
Hello @Firstbober I'm trying to reproduce your issue (using gpaste too) but I can't. Could you please show us your gpaste settings?

Thanks!

**Comment by Firstbober** [comment] 2022-08-23 12:37
Here are all the settings I could've found.

![image](https://user-images.githubusercontent.com/22197465/186159374-aec7a9c0-5876-4dc4-af02-392565735499.png)
![image](https://user-images.githubusercontent.com/22197465/186159452-2502cab9-f41d-443c-98dd-7ddc989b241f.png)
![image](https://user-images.githubusercontent.com/22197465/186159468-0dcaffc0-4707-4225-9004-64b2128b9224.png)

**Comment by madalenapmelo-kp** [comment] 2024-04-03 09:19
Hi @Firstbober,

Could you please confirm if you are still experiencing this behavior and, if not, close this issue?

**Closed as not planned** 2024-04-24 10:08 UTC
Labels: bug
