### ISSUE TITLE
bug: redirect to libraries-templates don't work

### ISSUE THREAD

**Issue by prKassad** [uxbox/uxbox#4625] opened 2024-05-24 09:59 UTC
### Steps To Reproduce

1. go to https://design.penpot.app/
2. open `Libraries` in NavBar
3. when libraries section is empty, click on link `Libraries & templates.`

When GET parameters are passed, redirect from `https://penpot.app/libraries-templates.html?_gl=someParamContent` don't work. 

### Expected behavior

Redirect to https://penpot.app/libraries-templates

### Actual behavior

Server return 404 Not found

### Screenshots or video

![image](https://github.com/penpot/penpot/assets/6651925/51e9016a-5348-457c-a651-997ef5ac8008)
![image](https://github.com/penpot/penpot/assets/6651925/83e52c31-9f22-47e9-bb3c-ff7a43a29072)

**Comment by madalenapmelo-kp** [comment] 2024-05-28 12:46
Hi @prKassad,

Thanks for reporting this! The issue is now fixed!

**Closed as completed by madalenapmelo-kp** 2024-05-28 12:46 UTC
Labels: bug
