### ISSUE TITLE
bug: still a bug at positionning in nested boards

### ISSUE THREAD

**Issue by NicolasLeboeuf** [uxbox/uxbox#3499] opened 2023-08-07 12:42 UTC
### Steps To Reproduce

1. create several layers of nested boards
2. add a board to "toggle overlay" on it
3. place it in the prototype it where it should
4. doesn't work properly, the coordinates are based on the main board instead of the parent

### Expected behavior

The board is placed where the ghost is placed

### Actual behavior

The board is placed according to the top parent.

### Screenshots or video

Nested boards:
![image](https://github.com/penpot/penpot/assets/62602652/e49effb7-10a9-460b-b1bb-66df29f52ab8)

How I need to place the target
![Capture d’écran du 2023-08-07 14-12-19](https://github.com/penpot/penpot/assets/62602652/aa813289-6401-4400-8a3a-d6fffb7d5ab4)

The result
![Capture d’écran du 2023-08-07 14-31-55](https://github.com/penpot/penpot/assets/62602652/c65b63f4-0a7a-4e99-a77e-1256aaee2dbe)

### Desktop (please complete the following information)

Ubuntu 22.04
Chrome 115

### Additional context

Bug still present after fixing https://github.com/penpot/penpot/issues/3114 and https://github.com/penpot/penpot/issues/3003

**Comment by EsterLatorre** [comment] 2023-08-08 07:50
Hello Nicolas,
Thanks for your report, it seems to be broken again. I've logged it [here](https://tree.taiga.io/project/penpot/issue/5720) with high priority.
Have a good day!

**Comment by madalenapmelo-kp** [comment] 2024-02-22 14:45
Hi @NicolasLeboeuf,

Could you please confirm if the issue is fixed and, if so, close this issue? Thank you in advance :)

**Closed as completed** 2024-05-07 12:09 UTC
Labels: bug, managed on taiga
