### ISSUE TITLE
bug: Crash when using typography styles

### ISSUE THREAD

**Issue by lplath** [uxbox/uxbox#5486] opened 2024-12-19 10:33 UTC
### Steps To Reproduce

1. Create a new file
2. Create a typography style and apply it to a text element

The following actions cause the penpot to crash:
- Editing the text content
- Applying a new typographic style
- Adding a new typographic style to the library while selecting a text element (if no text is selected, this works fine)
- Unlinking the style

### Expected behavior

See above

### Actual behavior

Internal Error

### Desktop (please complete the following information)

- Chrome 131 & Firefox 133

### Environment (please complete the following information)

Hosted (https://penpot.app/)

### Frontend Stack Trace

```console
Hint:    2024-12-19T11:20:46.179+01:00 is not ISeqable
Prof ID: ac9887f0-abe5-11eb-bb49-81aaa3a367f9
Team ID: ace76b40-abe5-11eb-bb49-81aaa3a367f9

Data:
{:hint "2024-12-19T11:20:46.179+01:00 is not ISeqable"}

Trace:
Error: 2024-12-19T11:20:46.179+01:00 is not ISeqable
  at PENPOT.nc (https://design.penpot.app/js/shared.377f636b8-1734525476.js:139:416)
  at PENPOT.ce.Wa (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1891:77)
  at Pga (https://design.penpot.app/js/shared.377f636b8-1734525476.js:176:258)
  at PENPOT.g.ma (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1847:24)
  at PENPOT.nc (https://design.penpot.app/js/shared.377f636b8-1734525476.js:139:202)
  at h (https://design.penpot.app/js/shared.377f636b8-1734525476.js:2137:218)
  at h (https://design.penpot.app/js/shared.377f636b8-1734525476.js:2137:124)
  at h (https://design.penpot.app/js/shared.377f636b8-1734525476.js:2137:124)
  at https://design.penpot.app/js/shared.377f636b8-1734525476.js:1891:384
  at PENPOT.ce.Wa (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1891:389)
  at Pga (https://design.penpot.app/js/shared.377f636b8-1734525476.js:176:258)
  at PENPOT.g.ma (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1847:24)
  at PENPOT.nc (https://design.penpot.app/js/shared.377f636b8-1734525476.js:139:202)
  at h (https://design.penpot.app/js/shared.377f636b8-1734525476.js:2137:218)
  at h (https://design.penpot.app/js/shared.377f636b8-1734525476.js:2137:124)
  at PENPOT.wi.l (https://design.penpot.app/js/shared.377f636b8-1734525476.js:2137:484)
  at Object.wi (https://design.penpot.app/js/shared.377f636b8-1734525476.js:2135:275)
  at eval (/js/main-workspace.377f636b8-1734525476.js:519:173)
  at F5.O (/js/main-workspace.377f636b8-1734525476.js:519:192)
  at cVa (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1258:45)
  at https://design.penpot.app/js/shared.377f636b8-1734525476.js:3782:15
  at PENPOT.g.ai (https://design.penpot.app/js/shared.377f636b8-1734525476.js:3757:562)
  at PENPOT.TE.h (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1751:56)
  at Object.TE (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1750:124)
  at PENPOT.Og.h (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1886:110)
  at d (https://design.penpot.app/js/shared.377f636b8-1734525476.js:3781:509)
  at Object.next (https://design.penpot.app/js/shared.377f636b8-1734525476.js:3782:450)
  at oF.next (https://design.penpot.app/js/libs.js?ts=1734526108506:592:2258)
  at e._next (https://design.penpot.app/js/libs.js?ts=1734526108506:592:1644)
  at e.next (https://design.penpot.app/js/libs.js?ts=1734526108506:592:1370)
  at ic.next (https://design.penpot.app/js/libs.js?ts=1734526108506:592:7147)
  at Object.next (https://design.penpot.app/js/libs.js?ts=1734526108506:592:23948)
  at oF.next (https://design.penpot.app/js/libs.js?ts=1734526108506:592:2258)
  at e._next (https://design.penpot.app/js/libs.js?ts=1734526108506:592:1644)
  at e.next (https://design.penpot.app/js/libs.js?ts=1734526108506:592:1370)
  at e.next [as _nextOverride] (https://design.penpot.app/js/libs.js?ts=1734526108506:592:25684)
  at e.Lut [as _next] (https://design.penpot.app/js/libs.js?ts=1734526108506:592:1873)
  at e.next (https://design.penpot.app/js/libs.js?ts=1734526108506:592:1370)
  at ic.next (https://design.penpot.app/js/libs.js?ts=1734526108506:592:7147)
  at z.next (https://design.penpot.app/js/shared.377f636b8-1734525476.js:3783:38)
  at https://design.penpot.app/js/shared.377f636b8-1734525476.js:3771:60
  at https://design.penpot.app/js/shared.377f636b8-1734525476.js:284:67
  at wd (https://design.penpot.app/js/shared.377f636b8-1734525476.js:164:211)
  at PENPOT.g.Pb (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1838:239)
  at PENPOT.Fb (https://design.penpot.app/js/shared.377f636b8-1734525476.js:166:259)
  at PENPOT.Mg (https://design.penpot.app/js/shared.377f636b8-1734525476.js:284:32)
  at IK.l (https://design.penpot.app/js/shared.377f636b8-1734525476.js:3771:36)
  at IK.X (https://design.penpot.app/js/shared.377f636b8-1734525476.js:3771:179)
  at PENPOT.ve.j (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1863:274)
  at PENPOT.Y.l (https://design.penpot.app/js/shared.377f636b8-1734525476.js:3785:452)

Last events:
[":app.main.data.workspace.collapse/expand-all-parents"
 ":app.main.data.workspace.selection/select-shape"
 ":app.main.data.workspace.selection/deselect-all"
 ":app.main.data.workspace.selection/handle-area-selection"
 ":app.main.data.workspace.selection/select-shapes-by-current-selrect"
 ":app.main.data.workspace.viewport/finish-panning"
 ":app.main.data.workspace.zoom/finish-zooming"
 ":app.main.data.workspace.selection/update-selrect"
 ":app.main.data.workspace.guides/set-hover-guide"
 ":app.main.data.workspace/workspace-focus-lost"
 ":app.main.data.workspace.undo/check-open-transactions"
 ":app.main.data.workspace.transforms/start-move-selected"
 ":app.main.data.workspace.viewport/finish-panning"
 ":app.main.data.workspace.zoom/finish-zooming"
 ":app.main.data.workspace.collapse/expand-all-parents"
 ":app.main.data.workspace.selection/select-shape"
 ":app.main.data.workspace.transforms/start-move-selected"
 ":app.main.data.workspace.viewport/finish-panning"
 ":app.main.data.workspace.zoom/finish-zooming"
 ":app.main.data.workspace.collapse/expand-all-parents"
 ":app.main.data.workspace.selection/select-shape"
 ":app.main.data.workspace.collapse/expand-all-parents"
 ":app.main.data.workspace.selection/select-shape"
 ":app.main.data.workspace.edition/start-edition-mode"
 ":app.main.data.workspace/start-editing-selected"
 ":app.main.data.workspace.texts/update-editor"
 ":app.main.data.workspace.texts/update-editor-state"
 ":app.main.data.workspace.texts/initialize-editor-state"
 ":app.main.data.workspace.texts/editor-select-all"
 ":app.main.data.shortcuts/push-shortcuts"
 ":app.main.data.workspace.texts/update-text-modifier"
 ":app.main.data.workspace.texts/update-editor"
 ":app.main.data.workspace.colors/stop-picker"
 ":app.main.data.modal/hide-modal"
 ":app.main.data.notifications/hide"
 ":app.main.data.workspace.notifications/finalize"
 ":app.main.data.workspace.shape-layout/finalize"
 ":app.main.data.workspace/finalize-file"
 ":app.main.data.workspace/finalize-page"
 ":app.main.data.shortcuts/pop-shortcuts"
 ":app.main.data.workspace.undo/start-undo-transaction"
 ":app.main.data.workspace.guides/move-frame-guides"
 ":app.main.data.workspace.comments/move-frame-comment-threads"
 ":app.main.data.workspace.shapes/update-shapes"
 ":app.main.data.workspace.modifiers/clear-local-transform"
 ":app.main.data.workspace.undo/commit-undo-transaction"
 ":app.main.data.workspace.modifiers/apply-modifiers"
 ":app.main.data.workspace.texts/remove-text-modifier"
 ":app.main.data.events/event"
 ":app.main.data.workspace.modifiers/update-modifiers"
 ":app.main.data.workspace.texts/commit-update-text-modifier"]
```

**Comment by madalenapmelo-kp** [comment] 2024-12-19 11:18
Hi @lplath,

Thanks for reporting this! We've added this to our backlog on Taiga so that we can look further into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/9612

**Comment by 72dpigraphics** [comment] 2024-12-19 15:47
I have the same issue and cant work on any of my projectfiles. (Seems like the problem is present since 18.12.2024, before everything worked fine)

If I try to edit or copy a Textelement with a typographic style (add, remove) or try to delete a typographic style the App crash. (Interal Error) - **It occures on all of my existing files**

Seems like there are several people with the same problem. 

[https://community.penpot.app/t/app-crash-on-text-edit-with-text-style-and-colour-style/7398/2](https://community.penpot.app/t/app-crash-on-text-edit-with-text-style-and-colour-style/7398/2)

Hope you can fix this bug soon

**Comment by Lobbel** [comment] 2024-12-19 20:45
I seem to have the same Issue. I wanted to replace all "hardcoded" textboxes to typography styles -> assigning the typography styles works, I can edit those styles, but editing the text (even trying to unlink from the style) leads to an immediate crash.
I'm using Penpot desktop on windows 11

**Comment by mfgoes** [comment] 2024-12-19 22:40
Just adding to say I have the same issue, however my bugreport looks a bit different:
```
Hint:    a.lb is not a function
Prof ID: 00c92ba6-454d-8098-8005-73638b34b4f3
Team ID: 00c92ba6-454d-8098-8005-73638b352385

Data:
{:hint "a.lb is not a function"}

Trace:
TypeError: a.lb is not a function
  at PENPOT.Lc (https://design.penpot.app/js/shared.377f636b8-1734525476.js:148:224)
  at Dma (https://design.penpot.app/js/shared.377f636b8-1734525476.js:361:476)
  at eJa (https://design.penpot.app/js/shared.377f636b8-1734525476.js:2636:513)
```

**Comment by 72dpigraphics** [comment] 2024-12-20 06:25
```
Hint:    2024-12-16T15:52:11.820+01:00 is not ISeqable
Prof ID: e6ff91c0-8d79-11eb-9126-57893f4da933
Team ID: 09a84000-8d7a-11eb-9126-57893f4da933

Data:
{:hint "2024-12-16T15:52:11.820+01:00 is not ISeqable"}

Trace:
Error: 2024-12-16T15:52:11.820+01:00 is not ISeqable
  at PENPOT.nc (https://design.penpot.app/js/shared.377f636b8-1734525476.js:139:416)
  at PENPOT.ce.Wa (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1891:77)
  at Pga (https://design.penpot.app/js/shared.377f636b8-1734525476.js:176:258)
  at PENPOT.g.ma (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1847:24)
  at PENPOT.nc (https://design.penpot.app/js/shared.377f636b8-1734525476.js:139:202)
  at h (https://design.penpot.app/js/shared.377f636b8-1734525476.js:2137:218)
  at h (https://design.penpot.app/js/shared.377f636b8-1734525476.js:2137:124)
  at h (https://design.penpot.app/js/shared.377f636b8-1734525476.js:2137:124)
  at https://design.penpot.app/js/shared.377f636b8-1734525476.js:1891:384
  at PENPOT.ce.Wa (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1891:389)
  at Pga (https://design.penpot.app/js/shared.377f636b8-1734525476.js:176:258)
  at PENPOT.g.ma (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1847:24)
  at PENPOT.nc (https://design.penpot.app/js/shared.377f636b8-1734525476.js:139:202)
  at h (https://design.penpot.app/js/shared.377f636b8-1734525476.js:2137:218)
  at h (https://design.penpot.app/js/shared.377f636b8-1734525476.js:2137:124)
  at PENPOT.wi.l (https://design.penpot.app/js/shared.377f636b8-1734525476.js:2137:484)
  at Object.wi (https://design.penpot.app/js/shared.377f636b8-1734525476.js:2135:275)
  at eval (/js/main-workspace.377f636b8-1734525476.js:519:173)
  at F5.O (/js/main-workspace.377f636b8-1734525476.js:519:192)
  at cVa (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1258:45)
  at https://design.penpot.app/js/shared.377f636b8-1734525476.js:3782:15
  at PENPOT.g.ai (https://design.penpot.app/js/shared.377f636b8-1734525476.js:3757:562)
  at PENPOT.TE.h (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1751:56)
  at Object.TE (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1750:124)
  at PENPOT.Og.h (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1886:110)
  at d (https://design.penpot.app/js/shared.377f636b8-1734525476.js:3781:509)
  at Object.next (https://design.penpot.app/js/shared.377f636b8-1734525476.js:3782:450)
  at oF.next (https://design.penpot.app/js/libs.js?ts=1734526108506:592:2258)
  at e._next (https://design.penpot.app/js/libs.js?ts=1734526108506:592:1644)
  at e.next (https://design.penpot.app/js/libs.js?ts=1734526108506:592:1370)
  at ic.next (https://design.penpot.app/js/libs.js?ts=1734526108506:592:7147)
  at Object.next (https://design.penpot.app/js/libs.js?ts=1734526108506:592:23948)
  at oF.next (https://design.penpot.app/js/libs.js?ts=1734526108506:592:2258)
  at e._next (https://design.penpot.app/js/libs.js?ts=1734526108506:592:1644)
  at e.next (https://design.penpot.app/js/libs.js?ts=1734526108506:592:1370)
  at e.next [as _nextOverride] (https://design.penpot.app/js/libs.js?ts=1734526108506:592:25684)
  at e.Lut [as _next] (https://design.penpot.app/js/libs.js?ts=1734526108506:592:1873)
  at e.next (https://design.penpot.app/js/libs.js?ts=1734526108506:592:1370)
  at ic.next (https://design.penpot.app/js/libs.js?ts=1734526108506:592:7147)
  at z.next (https://design.penpot.app/js/shared.377f636b8-1734525476.js:3783:38)
  at https://design.penpot.app/js/shared.377f636b8-1734525476.js:3771:60
  at https://design.penpot.app/js/shared.377f636b8-1734525476.js:284:67
  at wd (https://design.penpot.app/js/shared.377f636b8-1734525476.js:164:211)
  at PENPOT.g.Pb (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1838:239)
  at PENPOT.Fb (https://design.penpot.app/js/shared.377f636b8-1734525476.js:166:259)
  at PENPOT.Mg (https://design.penpot.app/js/shared.377f636b8-1734525476.js:284:32)
  at IK.l (https://design.penpot.app/js/shared.377f636b8-1734525476.js:3771:36)
  at IK.X (https://design.penpot.app/js/shared.377f636b8-1734525476.js:3771:179)
  at PENPOT.ve.j (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1863:274)
  at PENPOT.Y.l (https://design.penpot.app/js/shared.377f636b8-1734525476.js:3785:452)

Last events:
[":app.main.data.plugins/save-plugin-permissions-peek"
 ":app.main.data.workspace.thumbnails/update-thumbnail"
 ":app.main.data.workspace.selection/deselect-all"
 ":app.main.data.workspace.selection/handle-area-selection"
 ":app.main.data.workspace.selection/select-shapes-by-current-selrect"
 ":app.main.data.workspace.viewport/finish-panning"
 ":app.main.data.workspace.zoom/finish-zooming"
 ":app.main.data.workspace.collapse/expand-all-parents"
 ":app.main.data.workspace.selection/select-shape"
 ":app.main.data.workspace.selection/update-selrect"
 ":app.main.data.workspace.transforms/start-move-selected"
 ":app.main.data.workspace.viewport/finish-panning"
 ":app.main.data.workspace.zoom/finish-zooming"
 ":app.main.data.workspace.collapse/expand-all-parents"
 ":app.main.data.workspace.selection/select-shape"
 ":app.main.data.workspace.transforms/start-move-selected"
 ":app.main.data.workspace.viewport/finish-panning"
 ":app.main.data.workspace.zoom/finish-zooming"
 ":app.main.data.workspace.collapse/expand-all-parents"
 ":app.main.data.workspace.selection/select-shape"
 ":app.main.data.workspace.collapse/expand-all-parents"
 ":app.main.data.workspace.selection/select-shape"
 ":app.main.data.workspace.edition/start-edition-mode"
 ":app.main.data.workspace/start-editing-selected"
 ":app.main.data.workspace.texts/update-editor"
 ":app.main.data.workspace.texts/update-editor-state"
 ":app.main.data.workspace.texts/initialize-editor-state"
 ":app.main.data.workspace.texts/editor-select-all"
 ":app.main.data.shortcuts/push-shortcuts"
 ":app.main.data.workspace.texts/update-text-modifier"
 ":app.main.data.workspace.texts/update-editor"
 ":app.main.data.workspace.colors/stop-picker"
 ":app.main.data.modal/hide-modal"
 ":app.main.data.notifications/hide"
 ":app.main.data.workspace.notifications/finalize"
 ":app.main.data.workspace.shape-layout/finalize"
 ":app.main.data.workspace/finalize-file"
 ":app.main.data.workspace/finalize-page"
 ":app.main.data.shortcuts/pop-shortcuts"
 ":app.main.data.workspace.undo/start-undo-transaction"
 ":app.main.data.workspace.guides/move-frame-guides"
 ":app.main.data.workspace.comments/move-frame-comment-threads"
 ":app.main.data.workspace.shapes/update-shapes"
 ":app.main.data.workspace.modifiers/clear-local-transform"
 ":app.main.data.workspace.undo/commit-undo-transaction"
 ":app.main.data.workspace.modifiers/apply-modifiers"
 ":app.main.data.workspace.texts/remove-text-modifier"
 ":app.main.data.workspace/set-margins-selected"
 ":app.main.data.events/event"
 ":app.main.data.workspace.modifiers/update-modifiers"
 ":app.main.data.workspace.texts/commit-update-text-modifier"]


```

**Comment by madalenapmelo-kp** [comment] 2024-12-23 09:52
This issue has been fixed and the fix will be released soon!

**Closed as completed by madalenapmelo-kp** 2024-12-23 09:52 UTC
Labels: bug, managed on taiga
