### ISSUE TITLE
bug: unexpected behaviour when duplicating elements

### ISSUE THREAD

**Issue by schalkneethling** [uxbox/uxbox#2423] opened 2022-10-08 16:52 UTC
### Steps To Reproduce

1. Create a set of elements, say, a list of colored squares
2. Create a duplicate of the above and color them different from the previous set
3. Select the second row
4. Hold in option/alt and click and drag to duplicate elements
5. One of the elements in the new group switches back to a previous color

### Expected behavior

The new set retains all the same colors as the set from which it was duplicated.

### Actual behavior

See the steps to reproduce.

### Screenshots or video

https://user-images.githubusercontent.com/10350960/194718533-30203843-500f-4fdf-9016-0984069a7eca.mp4

### Desktop (please complete the following information)

- OS: macOS
- Browser: Arc Version 0.71.0 (35084) Chromium Engine Version 106.0.5249.103

### Environment (please complete the following information)

https://design.penpot.app

**Comment by EsterLatorre** [comment] 2022-10-10 07:25
Hello schalkneethling,

I've added your feedback to the backlog. You can track its evolution here: https://tree.taiga.io/project/penpot/issue/4311.
Because this bug seems very arbitrary and may not reproduce well if we try to replicate it, it may help us if you can send us that file ;)

Thanks for your feedback!

**Comment by schalkneethling** [comment] 2022-10-21 18:56
> Hello schalkneethling,
> 
> I've added your feedback to the backlog. You can track its evolution here: https://tree.taiga.io/project/penpot/issue/4311. Because this bug seems very arbitrary and may not reproduce well if we try to replicate it, it may help us if you can send us that file ;)
> 
> Thanks for your feedback!

Hey @EsterLatorre, would be happy to. Will take a look. I worked on a new design file and was able to replicate the problem without trying. Will create an isolated design file and see if I can replicate it in there.

**Comment by pabloalba** [comment] 2022-12-30 08:22
Hi @schalkneethling . I'm unable to reproduce this. Can you send a .penpot file that replicates the problem to support@penpot.app?

Thank you!

**Comment by pabloalba** [comment] 2023-02-08 11:56
Still can't reproduce it, and we haven't more info. I'm closing it, feel free to reopen if it happens again

**Closed as completed by pabloalba** 2023-02-08 11:56 UTC
Labels: bug, managed on taiga
