### ISSUE TITLE
Odd rendering on non-hovered boards

### ISSUE THREAD

**Issue by LauraWebdev** [uxbox/uxbox#2348] opened 2022-09-26 15:05 UTC
**Steps to reproduce**
1. Open a penpot file with multiple boards
2. Hover over one board, then hover over another

**Expected behavior**
The board does not look significantly different.

**Actual behavior**
1. All elements are blurry
2. Some elements are significantly shifted in their position
3. Some svg icons are displayed as black.
 
**Screenshots**
Hovering over "Search"
![image](https://user-images.githubusercontent.com/7365286/192312210-77c0ee09-28a7-4563-9763-bd9d88550110.png)

Hovering over "Dashboard"
![image](https://user-images.githubusercontent.com/7365286/192312244-dd7b323e-b3d6-4eea-b7ed-fcd8a1097bb7.png)

**Desktop (please complete the following information):**
- OS (e.g. iOS): Windows 11 latest
- Browser & version (e.g. Chrome 89.0): Microsoft Edge latest

**Environment (please complete the following information):**
- Host (e.g. https://design.penpot.app, local instance): any

**Comment by LauraWebdev** [comment] 2022-09-26 15:05
I've also made a video where I'm hovering over the boards to show how much they visually differ.

https://user-images.githubusercontent.com/7365286/192312511-a9b54291-aae8-4d3f-bfff-8c4780574c0d.mp4

**Comment by superalex** [comment] 2022-09-27 06:53
Thank you very much @LauraWebdev 

I think there are two mixed issues here:

1.- The blurry effect: this related to thumbnails. SVG can have a poor performance in your browser when you manage too many elements, one of the things we do to improve it is only painting what is needed. The selected board is fully rendered, but the rest are rendered as images (each board has its own thumbnail associated). When hovering another frame we replace the thumbnail with the real svg content. That's the reason why you see that small difference. Anyway we keep working with every release to improve this :)

2.- The svg icons displayed as black sounds like a possible bug. Could you please include one of those svgs?. I've been trying to reproduce the issue with some of them but I can't.

**Comment by LauraWebdev** [comment] 2022-09-27 10:01
I am using the materialdesignicons.com svg output and add a group fill

**Comment by superalex** [comment] 2022-09-30 05:14
Hi @LauraWebdev !

I've used one of those svg icons and still can't reproduce it...Could you please post the file url where this is happening?


https://user-images.githubusercontent.com/1579633/193195193-4d9063b5-14a5-44a6-a914-13407d547857.mp4



Regards,

**Comment by LauraWebdev** [comment] 2022-09-30 07:45
Yeah sure, here's the project. The visual changes happen on all of my devices.: https://design.penpot.app/#/workspace/bc033c10-3efd-11ed-b414-cf2300df1f4f/9d4a6870-39d5-11ed-a5c2-cf2300df1f4f?page-id=b3224011-380d-11ed-b87a-4d344a790be9

**Comment by LauraWebdev** [comment] 2022-09-30 07:46
I've also just noticed that it only happens when your zoom is lower than 125% in that document.

**Comment by superalex** [comment] 2022-10-04 04:38
Hi @LauraWebdev 

I think I found the problem, the imported svg is using the currentColor:

![1](https://user-images.githubusercontent.com/1579633/193735128-7baad931-4974-4398-b921-bec58c8f788e.png)

As a workaround if you remove the imported attribute (with the - icon) and set the background properly icons are desplayed ok. I'm still investigating what can be happening with the thumbnail generation here :)

**Comment by superalex** [comment] 2022-10-04 07:02
Then taiga link to track it -> https://tree.taiga.io/project/penpot/issue/4286

**Comment by pabloalba** [comment] 2022-12-30 08:23
Hi! We've fixed the SVG import to fix this. It will be released soon!

**Closed as completed** 2023-01-31 13:47 UTC
Labels: bug, managed on taiga
