### ISSUE TITLE
White space appears in view mode when accessed from mobile view in browser developer tools

### ISSUE THREAD

**Issue by shahrin014** [uxbox/uxbox#1396] opened 2021-12-10 01:04 UTC
**Describe the bug**
When viewing on Chrome using the mobile responsive view in developer tools, there is a white space at the bottom of the screen.

**To Reproduce**
1.  Run penpot from docker (not sure if this applies to penpot web)
2.  Open Chrome browser
3.  Access developer tools
4.  Change resolution to mobile (I used iPhone X)
5.  Go to view mode
6.  See white space at the bottom of the screen

**Expected behavior**
The space should not be there.

**Screenshots**
<img width="1904" alt="Screen Shot 2021-12-10 at 9 59 28" src="https://user-images.githubusercontent.com/17451563/145499614-ff26edb8-10a7-4fc6-9f61-ba053e0097a4.png">

**Desktop (please complete the following information):**

-  Mac OSX
-  Chrome
-  Version 96.0.4664.93 (Official Build) (x86_64)

**Comment by EvaMarco** [comment] 2021-12-20 15:13
Hello @shahrin014, we have opened a bug issue in taiga to manage both of your issues about white and black empty space, you can check it [here](https://tree.taiga.io/project/penpot/issue/2379). Thanks for your warning.

**Comment by pabloalba** [comment] 2022-03-23 11:34
Hi, @shahrin014 

I can't reproduce this issue. Maybe it's already fixed as a result of some other changes. Can you verify if this is still happening to you? Thxs!

**Comment by pabloalba** [comment] 2022-05-05 11:11
We can't reproduce it so I'm gonna close it. If it happens again, please tell us!

**Closed as completed by pabloalba** 2022-05-05 11:11 UTC
Labels: bug, managed on taiga
