### ISSUE TITLE
bug: bad gateway with server ip using docker installation and get error using nginx as reverse proxy and backend connection refused

### ISSUE THREAD

**Issue by D4ykoo** [uxbox/uxbox#3033] opened 2023-03-10 21:08 UTC
### Steps To Reproduce

I followed the installation instructions with docker and did not configure anything for testing reasons.

For the user creation: 
`docker exec -ti penpot-penpot-backend-1 python3 ./manage.py create-profile`

### Expected behavior

No error, home screen of penpot/ user login.

### Actual behavior

I guess all problems are related, thats why they are in one issue documented.

### First Problem
I get an bad gateway page if I access penpot with `http://<ip>:9001` or using a domain pointing to my reverse proxy with nginx e.g. `https://penpot.domain.com`.

### Third Problem
Further I can not create a first user with this command: 
`docker exec -ti penpot-penpot-backend-1 python3 ./manage.py create-profile`
instead i am recieving this error after adding the credentials:
`Traceback (most recent call last):
  File "/opt/penpot/backend/./manage.py", line 147, in <module>
    create_profile(fullname, email, password)
  File "/opt/penpot/backend/./manage.py", line 79, in create_profile
    res = run_cmd(params)
  File "/opt/penpot/backend/./manage.py", line 62, in run_cmd
    res, failed = send_eval(expr)
  File "/opt/penpot/backend/./manage.py", line 41, in send_eval
    s.connect((host, port))
ConnectionRefusedError: [Errno 111] Connection refused`

### The `http` problem:
![Screenshot 2023-03-10 215347](https://user-images.githubusercontent.com/50523358/224426487-1efafcb0-428f-496c-8db7-5edf8330d7a1.png)

### The ``https` problem:
![Screenshot 2023-03-10 214534](https://user-images.githubusercontent.com/50523358/224425920-d65a065c-40cf-4db5-8761-7300fdaf0a07.png)

### Desktop (please complete the following information)

Browser: Firefox v110.0.1 & Chrome

### Environment (please complete the following information)

- Host : `https://penpot.domain.com` and `http://<ip>:9001
`
It is self-hosted:
- OS Version : Debian GNU/Linux 11 (bullseye) aarch64 --> RPI 4 with official 64-bit RPI os image
- Memory: 8gb 
- CPU: ARM64
- Docker version:  23.0.1-ce
- Docker compose version: v2.16.0

Docker compose file was not changed.

NGINX Config: 
```
map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}

server {      
  server_name     penpot.domain.com; 
  access_log      /var/log/nginx/penpot.access.log;
  error_log       /var/log/nginx/penpot.error.log;

  ignore_invalid_headers off;

  location / {
      sendfile off;
      proxy_pass         http://127.0.0.1:9001;
      proxy_redirect     default;
      proxy_http_version 1.1;

      # Required for Jenkins websocket agents
      proxy_set_header   Connection        $connection_upgrade;
      proxy_set_header   Upgrade           $http_upgrade;

      proxy_set_header   Host              $host;
      proxy_set_header   X-Real-IP         $remote_addr;
      proxy_set_header   X-Forwarded-Host  $host;
      proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
      proxy_set_header   X-Forwarded-Proto $scheme;
      proxy_max_temp_file_size 0;

      #this is the maximum upload size
      client_max_body_size       10m;
      client_body_buffer_size    128k;

      proxy_connect_timeout      90;
      proxy_send_timeout         90;
      proxy_read_timeout         90;
      proxy_buffering            off;
      proxy_request_buffering    off; # Required for HTTP CLI commands
      proxy_set_header Connection ""; # Clear for keepalive
  }
}
```

### Additional context

I am open to every help, it may be just my fault of configuration but i read in another issue (someone requested an even more complex compose file) that it should at least work with `http`.

If they are any other questions feel free to contact me.

**Comment by niwinz** [comment] 2023-03-11 21:25
Hello @D4ykoo 

Looks like backend is unable to start but no backend logs are provided so I don't know the cause. This is the reason you can't execute the create-profile.

**Comment by D4ykoo** [comment] 2023-03-11 21:52
Hello @niwinz, thanks for the response!

Here is the docker log from the backend:
[penpot-backend.log](https://github.com/penpot/penpot/files/10949521/penpot-backend.log)

These lines are always repeating:
```
2023-03-11 21:28:45,651 main INFO Registered Log4j as the java.util.logging.LogManager.
[2023-03-11 21:28:58.033] I app.metrics - action="initialize metrics"
[2023-03-11 21:28:58.219] I app.db - hint="initialize connection pool", name="main", uri="postgresql://penpot-postgres/penpot", read-only=false, with-credentials=true, min-size=0, max-size=60
2023-03-11 21:29:17,626 main INFO Registered Log4j as the java.util.logging.LogManager.
[2023-03-11 21:29:29.891] I app.metrics - action="initialize metrics"
[2023-03-11 21:29:30.048] I app.db - hint="initialize connection pool", name="main", uri="postgresql://penpot-postgres/penpot", read-only=false, with-credentials=true, min-size=0, max-size=60
2023-03-11 21:29:49,512 main INFO Registered Log4j as the java.util.logging.LogManager.
[2023-03-11 21:30:02.699] I app.metrics - action="initialize metrics"
[2023-03-11 21:30:02.832] I app.db - hint="initialize connection pool", name="main", uri="postgresql://penpot-postgres/penpot", read-only=false, with-credentials=true, min-size=0, max-size=60
2023-03-11 21:30:22,134 main INFO Registered Log4j as the java.util.logging.LogManager.
[2023-03-11 21:30:35.055] I app.metrics - action="initialize metrics"
[2023-03-11 21:30:35.244] I app.db - hint="initialize connection pool", name="main", uri="postgresql://penpot-postgres/penpot", read-only=false, with-credentials=true, min-size=0, max-size=60
2023-03-11 21:30:54,454 main INFO Registered Log4j as the java.util.logging.LogManager.
```

**Comment by VVege** [comment] 2023-03-15 08:11
i have the save problem . docker 19.03.13. docker-compose v2.12.2

**Comment by niwinz** [comment] 2023-03-15 09:06
Hmm, still don't know what problem causing it. Please paste the docker ps output, look which containers are started and which no. 
The log looks incomplete and indicates that backend is unable to start, and this is 99% probably external cause: I mean no being able to connect database, no enough memory, OOM killer kills the backend process all the time...

**Comment by VVege** [comment] 2023-03-15 11:13
docker ps

> 

> 

CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                            PORTS                              NAMES
e8bff7c82956        penpotapp/frontend:latest   "/bin/bash /entrypoi…"   31 seconds ago      Up 28 seconds                     0.0.0.0:9001->80/tcp               penpot-penpot-frontend-1
db97e055bee2        penpotapp/backend:latest    "/bin/bash run.sh"       31 seconds ago      Restarting (1) 11 seconds ago                                        penpot-penpot-backend-1
d1fc91930498        postgres:15                 "docker-entrypoint.s…"   31 seconds ago      Up 29 seconds                     5432/tcp                           penpot-penpot-postgres-1
1c459c971f6c        sj26/mailcatcher:latest     "mailcatcher --foreg…"   31 seconds ago      Up 29 seconds                     1025/tcp, 0.0.0.0:1080->1080/tcp   penpot-penpot-mailcatch-1
aca66965fc2d        redis:7                     "docker-entrypoint.s…"   31 seconds ago      Up 29 seconds                     6379/tcp                           penpot-penpot-redis-1
4e090eaada38        penpotapp/exporter:latest   "node app.js"            31 seconds ago      Restarting (139) 12 seconds ago                                      penpot-penpot-exporter-1

---------------------------------------
**backend and exporter always restarting**

error log:
backend container:
docker logs db97e055bee2
+ exec /opt/jdk/bin/java -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -Dlog4j2.configurationFile=log4j2.xml -XX:-OmitStackTraceInFastThrow -jar penpot.jar -m app.main
[0.011s][warning][os,thread] Failed to start thread "GC Thread#0" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
[0.012s][error  ][gc,task  ] Failed to create worker thread
+ exec /opt/jdk/bin/java -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -Dlog4j2.configurationFile=log4j2.xml -XX:-OmitStackTraceInFastThrow -jar penpot.jar -m app.main
[0.008s][warning][os,thread] Failed to start thread "GC Thread#0" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
[0.009s][error  ][gc,task  ] Failed to create worker thread
+ exec /opt/jdk/bin/java -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -Dlog4j2.configurationFile=log4j2.xml -XX:-OmitStackTraceInFastThrow -jar penpot.jar -m app.main
[0.007s][warning][os,thread] Failed to start thread "GC Thread#0" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
[0.008s][error  ][gc,task  ] Failed to create worker thread
+ exec /opt/jdk/bin/java -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -Dlog4j2.configurationFile=log4j2.xml -XX:-OmitStackTraceInFastThrow -jar penpot.jar -m app.main
[0.008s][warning][os,thread] Failed to start thread "GC Thread#0" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
[0.008s][error  ][gc,task  ] Failed to create worker thread
+ exec /opt/jdk/bin/java -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -Dlog4j2.configurationFile=log4j2.xml -XX:-OmitStackTraceInFastThrow -jar penpot.jar -m app.main
[0.007s][warning][os,thread] Failed to start thread "GC Thread#0" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
[0.008s][error  ][gc,task  ] Failed to create worker thread
------------------------------------------------
**exporter container error logs**

node[1]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0xb6e500 node::Abort() [node]
 2: 0xb6e57e  [node]
 3: 0xbda18e  [node]
 4: 0xbda260 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 5: 0xb2decb node::InitializeOncePerProcess(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, node::ProcessFlags::Flags) [node]
 6: 0xb2e4fb node::Start(int, char**) [node]
 7: 0x7f68808f1d90  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7f68808f1e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0xaaa86e _start [node]
node[1]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0xb6e500 node::Abort() [node]
 2: 0xb6e57e  [node]
 3: 0xbda18e  [node]
 4: 0xbda260 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 5: 0xb2decb node::InitializeOncePerProcess(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, node::ProcessFlags::Flags) [node]
 6: 0xb2e4fb node::Start(int, char**) [node]
 7: 0x7fe5dfc75d90  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7fe5dfc75e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0xaaa86e _start [node]
node[1]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0xb6e500 node::Abort() [node]
 2: 0xb6e57e  [node]
 3: 0xbda18e  [node]
 4: 0xbda260 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 5: 0xb2decb node::InitializeOncePerProcess(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, node::ProcessFlags::Flags) [node]

**Comment by niwinz** [comment] 2023-03-15 11:19
yep, this looks like that I have supposed.
This is not something penpot related, I mean, your environement/operating system is unable to strart JVM or nodejs.

https://github.com/adoptium/temurin-build/issues/2976 Looks like some incompatibilities between docker  and openjdk,

More info here:

https://github.com/adoptium/containers/issues/215#issuecomment-1142046045

**Comment by niwinz** [comment] 2023-03-15 11:22
This issue should be fixed if you upgrade docker to latest version

**Closed as completed by niwinz** 2023-03-15 11:22 UTC
Labels: bug

**Comment by VVege** [comment] 2023-03-15 11:49
> This issue should be fixed if you upgrade docker to latest version

yes,it work。thanks

**Comment by ljtnono** [comment] 2023-03-23 13:50
> This issue should be fixed if you upgrade docker to latest version

the same probelm, but there are no error logs in my backend log output
