### ISSUE TITLE
use the IP don't visit

### ISSUE THREAD

**Issue by sacus** [uxbox/uxbox#1666] opened 2022-03-08 15:35 UTC
OS： centos 7
docker version: 20.10.7
docker-compose version: 1.29.2

I modified the variable PENPOT_PUBLIC_URI=http://localhost:9001 in config.env as the server's intranet ip according to the documentation,

Then docker-compose -p penpot -f docker-compose.yaml up -d
and created the user with: docker exec -ti penpot_penpot-backend_1 ./manage.sh create-profile

Then I access the server's external network ip: 9001 on my own windows computer, but the user name and password are wrong. I have tested many times and the user name and password are wrong. I changed the variable PENPOT_PUBLIC_URI to the server's external network ip, but it didn't work.  and report the wrong username and password

**Comment by Miosame** [comment] 2022-03-09 02:18
duplicate of: https://github.com/penpot/penpot/issues/1447#issuecomment-1009862955 if you're accessing it via http

**Comment by sacus** [comment] 2022-03-09 06:54
ok,alread solved

**Closed as completed** 2022-03-09 06:53 UTC
Labels: bug
