### ISSUE TITLE
bug: color picker has no inputs for HSV values in 2.0

### ISSUE THREAD

**Issue by LucaVazz** [uxbox/uxbox#4394] opened 2024-04-09 20:02 UTC
### Steps To Reproduce

1. open the color picker
2. set to HSV mode
3. observe inputs

### Expected behavior

inputs for hue, value, saturation should be displayed, similar to Penpot v1

<img src="https://github.com/penpot/penpot/assets/4174525/c6c4c6fb-a09d-4b00-bffe-237f92870b89" width="200" />

### Actual behavior

only the inputs for red, green, blue are displayed

<img src="https://github.com/penpot/penpot/assets/4174525/d17e97d5-5bdc-4edf-a2ae-f02a52c00beb" width="200" />

### Desktop (please complete the following information)

- OS: Windows 10
- Browser: Vivaldi 6.6.3271.57 (Stable channel) (32-Bit)
   (Chrome 122.0.0.0)

### Smartphone (please complete the following information)

n/a

### Environment (please complete the following information)

`design.penpot.app`

### Frontend Stack Trace

```console
n/a
```

### Backend Stack Trace

```console
n/a
```

### Additional context

(Otherwise, Penpot 2.0 is great - congrats on the release 🥳 )

**Comment by madalenapmelo-kp** [comment] 2024-04-10 09:23
Hi @LucaVazz,

Thank you for reporting this! I've opened an issue on Taiga so that we can look into this, you can find the issue here: https://tree.taiga.io/project/penpot/issue/7433

**Comment by madalenapmelo-kp** [comment] 2024-04-11 08:43
Hi @LucaVazz,

The issue is now fixed and the inputs for HSV are available!

**Closed as completed by madalenapmelo-kp** 2024-04-11 08:43 UTC
Labels: bug, managed on taiga

**Comment by LucaVazz** [comment] 2024-11-09 15:00
Hey @madalenapmelo-kp,
unfortunately this issue has a regression at the version currently deployed for design.penpot.app :/   
It is again only possible to type in values for R G B but not for H S V.

<img width="250px" src="https://github.com/user-attachments/assets/a414c5c8-9664-4fa1-8d34-b8cccffb59e0" />   

Should this issue be re-opened or should I rather create a new one?
