### ISSUE TITLE
cropped shapes in preview

### ISSUE THREAD

**Issue by mjourdan** [uxbox/uxbox#1605] opened 2022-02-17 20:49 UTC
**To Reproduce**
Either open a project with firefox and press the play button, or go directly to preview from a sharing link.

Do some scrolling up and down.

**Expected behavior**
Things look as good as in edit mode.

**Actual behavior**
Some part of some shapes are missing.
 
**Screenshots**

![cropping_1_2022-02-17](https://user-images.githubusercontent.com/5346620/154567302-c6da31a3-7821-45a8-9d1b-b06352c0bbd4.png)
![cropping_2_2022-02-17](https://user-images.githubusercontent.com/5346620/154567316-c56e470a-9ddf-4727-a8e8-2dc176626a7d.png)

**Desktop (please complete the following information):**
- Fedora 35
- Firefox 96.0

**Environment (please complete the following information):**
- https://design.penpot.app

**Additional context:**

Could reproduce on a different computer with same software. Could also reproduce in tor browser, but not in gnome web. The exact same shapes are cropped every time.

Screenshots above are from this page:

https://design.penpot.app/#/view/66507270-f920-11eb-9ade-278287232ac9?page-id=899fa920-4fc0-11ec-94e3-f70ff0605cd6&section=interactions&index=0&share-id=cdafb6d0-5dc8-11ec-826f-e949c75b760d

**Comment by superalex** [comment] 2022-02-23 07:17
Hi!,

Hi, we've just created [a bug at Taiga](https://tree.taiga.io/project/penpot/issue/2929) to track this issue from here. Hopefully, it will be fixed soon. 

Thank you very much for reporting.

**Comment by aharish** [comment] 2022-02-23 08:34
Hello, I run a self-hosted version of Penpot and can confirm the exact same behaviour there too. Can confirm WebKit based browsers don't have issue. It seems to only affect Gecko based browsers.

Some additional context that I can provide is that this only happens when the zoom is more than 55%. Using either fullscreen or scale up to fit causes this.

I tried to use inspect element to see what the problem was, but the moment the browser window resized to accommodate the developer panel, the cut off was gone. I moved the developer panel to a different window and reloaded the page. Reproduced the cutoff by changing zoom and alt-tabbed to the developer window. The moment I highlighted an element using the dev panel, the preview fixed itself and the cutoff was gone.

**Comment by superalex** [comment] 2022-02-24 06:09
Thank you very much @aharish!

**Comment by superalex** [comment] 2022-03-22 06:39
Hi!,

I've been working on this issue and I think there isn't too much we can do on the penpot side. I found some workarounds but they don't work in the 100% of the situations. I've created a sample html file reproducing the issue and reported to firefox here (https://bugzilla.mozilla.org/show_bug.cgi?id=1760747). I hope they can't solve it soon.

Thank you very much for your help! :)

**Closed as completed by superalex** 2022-03-22 06:39 UTC
Labels: bug, managed on taiga

**Comment by mjourdan** [comment] 2022-03-27 19:23
I'll keep an eye on the Firefox issue. Thanks @superalex!

**Comment by superalex** [comment] 2022-03-28 04:49
You are welcome! :)
