### ISSUE TITLE
feature: Instantly activate drag and drop after clicking element

### ISSUE THREAD

**Issue by pr0pz** [uxbox/uxbox#4514] opened 2024-04-24 16:32 UTC
### Is your feature request related to a problem? Please describe.

I want to be able to directly move things around the canvas while clicking it just one time. It's annoying on the long run (while effectively working) to have to click on an element a second time to be able to drag and drop it around the canvas (see video)

https://github.com/penpot/penpot/assets/48486059/30284218-3769-4cbe-a91f-82e32f46156b

### Describe the solution you'd like.

I'd like to instantly be able to drag and drop an element after clicking and holding the mouse while selecting the element.

**Comment by eeropic** [comment] 2024-04-26 09:34
Duplicate of https://github.com/penpot/penpot/issues/4440

**Closed as completed** 2024-04-29 07:26 UTC
Labels: enhancement
