### ISSUE TITLE
Internal Server Error Page at arbitrary times, using SAAS version. Firefox and Edge tested. Error message in browser console

### ISSUE THREAD

**Issue by richardsdev** [uxbox/uxbox#1379] opened 2021-11-30 14:26 UTC
**Describe the bug**
Internal Server error page when interacting with various elements on the page. Not sure what actions actually trigger it. It seems to happen at arbitrary times.

**To Reproduce**
Steps to reproduce the behaviour:
1.  Use Penpot normally

**Expected behavior**
Penpot should not error out

**Desktop (please complete the following information):**

-   OS: Windows 10 Pro, 20H2 build 19042.1348
-   Browser: Edge Version 96.0.1054.34 (Official build) (64-bit) and Firefox 94.0.2 (64-bit)

**Environment (please complete the following information):**
Using SAAS (https://design.penpot.app)

**Additional context**

The browser console logs the following error when the app crashes:

"instrument.js:112 
        
       Error: No protocol method IEditableCollection.-as-transient defined for type object: (#uuid "dac8ee30-5144-11ec-8ef8-3944d40e4b49" #uuid "c82fe210-5144-11ec-8ef8-3944d40e4b49" #uuid "a2018f80-5144-11ec-8ef8-3944d40e4b49")
    at Kb (shared.4ad34ab5c.js:1466)
    at pc (shared.4ad34ab5c.js:1493)
    at Function.AC.C (shared.4ad34ab5c.js:2963)
    at main.4ad34ab5c.js:5235
    at qd (shared.4ad34ab5c.js:1582)
    at He.g.mb (shared.4ad34ab5c.js:1616)
    at Ob (shared.4ad34ab5c.js:1584)
    at S$ (main.4ad34ab5c.js:5234)
    at main.4ad34ab5c.js:5235
    at I.g.mb (shared.4ad34ab5c.js:1723)
    at Ob (shared.4ad34ab5c.js:1584)
    at S$ (main.4ad34ab5c.js:5234)
    at S1b (main.4ad34ab5c.js:5237)
    at Xc (shared.4ad34ab5c.js:1068)
    at fg (shared.4ad34ab5c.js:1082)
    at Pe (shared.4ad34ab5c.js:1081)
    at eg (shared.4ad34ab5c.js:1080)
    at Zj (shared.4ad34ab5c.js:1208)
    at Ti (shared.4ad34ab5c.js:1138)
    at lg (shared.4ad34ab5c.js:1138)
    at Qh (shared.4ad34ab5c.js:1131)
    at shared.4ad34ab5c.js:1040
    at d.unstable_runWithPriority (shared.4ad34ab5c.js:974)
    at Dd (shared.4ad34ab5c.js:1039)
    at Md (shared.4ad34ab5c.js:1040)
    at Wc (shared.4ad34ab5c.js:1039)
    at Ia (shared.4ad34ab5c.js:1211)
    at Ka (shared.4ad34ab5c.js:1010)
    at HTMLElement.v (main.4ad34ab5c.js:231)
(anonymous) @ instrument.js:112"

I am not sure what other info I can provide with regards to this error, it happens every few minutes on the file I was working on. I can provide a link to the file if required, but there is nothing fancy in it. I did use some inkscape SVGs and thought they might be causing the issue, but the problem persisted even after I removed them.

**Comment by niwinz** [comment] 2021-11-30 16:18
Hello @richardsdev 

There are two issues probably (the both have only technical explication). I have found the possible issue but I need confirm it. If you send us a "link" to the workspace (that will allow see the file-id) it will help us to check the internal data structure and find the cause.

**Comment by richardsdev** [comment] 2021-11-30 22:04
Hi, here is the link to the workspace: https://design.penpot.app/#/workspace/43f8edd0-47b6-11ec-bce8-dfb9a7b9ff1b/7a582620-47b6-11ec-bce8-dfb9a7b9ff1b?page-id=09722480-4c9b-11ec-a3f3-a7d7cf66ff7b

**Comment by niwinz** [comment] 2021-12-01 10:53
We are working in a fix on this. Looks like we have clearly a bug. Thanks for reporting

**Comment by richardsdev** [comment] 2021-12-03 11:26
Not sure if this further info will be useful, but I was looking at this file again today and noticed that the error is triggered when interacting with a specific layer. The "NAV" group within the "Home /Landing Page" artboard seems to be the culprit... Clicking on it or focussing on it via the layers panel triggers the "internal server error" message

**Comment by niwinz** [comment] 2021-12-03 11:35
Oh, this is a very specific feedback, Awesome. I think we found a bug and we fixed it (not deployed yet, we are testing right now); so I go to test it with this specific case. Thanks

**Comment by niwinz** [comment] 2021-12-03 14:15
We have deployed the fix,I think it should be fixed, please can you refresh the browser and try again?

**Comment by richardsdev** [comment] 2021-12-03 14:20
Wow that was fast. I have checked the file and it seems to be working fine again, no more error page. I moved the component around and moved layers around inside of it, no problems. Seems to be fixed. Thanks so much

**Comment by niwinz** [comment] 2021-12-03 14:25
Awesome! Then, i close this issue \o/

**Closed as completed by niwinz** 2021-12-03 14:25 UTC
Labels: bug
